version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: flagcamp
      MYSQL_PASSWORD: flagcamp
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  app:
    build: .
    container_name: go-app
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge



